# Artificial Neural Network

### Importing the libraries

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [6]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [7]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #independent variable
y = dataset.iloc[:, -1].values #dependent variable

In [8]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [9]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [10]:
#the gender column is being encoded to 0's and 1's using label encoder class
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [11]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [12]:
#the geography column is encoded using OneHotEncoder class
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [15]:
#the feature scaling is a very important step in deep learning
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [16]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


## Part 2 - Building the ANN

### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential() #tensorflow library, keras library ,models module, sequentail class

### Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
#units is the number of neurons here it is 6, and the activtion funtion used here is the rectiifer function which is represented by 'relu'

### Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
#units is the number of neurons here it is 1, and the activtion funtion used here is the rectiifer function which is represented by 'sigmoid'
#here the output variable or the dependent variable is 'Exited' and it has a binary value there we choose 'sigmoid' as the activation function

## Training the ANN

### Compiling the ANN

In [21]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#here stochastic gradient is used using adam optimizer
#for binary clssification the loss is 'binary_crossentropy , for categorical its going to categorical_crossentropy

### Training the ANN on the Training set

In [22]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) 

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6847 - accuracy: 0.5568
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4748 - accuracy: 0.7941
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4580 - accuracy: 0.7908
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4237 - accuracy: 0.8040
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4272 - accuracy: 0.8055
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4237 - accuracy: 0.8110
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4199 - accuracy: 0.8151
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4329 - accuracy: 0.8147
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4278 - accuracy: 0.8128
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4200 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set result of a single observation

By uing the above ANN model predict if the customer with the folllowing information will leave the bank or not:

Geography: France 
Credit Score: 600 
Gender : Male </br>
Age : 40 years old </br>
Tenure : 3 years </br>
Balance: 60000 </br> 
Number of products : 2 </br>
Does this customer have a credict card? yes </br>
Is this customer an Active Member: Yes </br>
Estimated Salary: $50000</br>
So should we say goodbye to that customer?</br>


In [35]:
print(ann.predict(sc.transform([[1, 0, 0, 600 , 1 , 40 , 3 , 60000 , 2 , 1 , 1 , 50000]])))

[[0.0283325]]


Therefore, our ANN model predicts that this customer stays in the bank! Because the probability of the customer leaving the bank is almost 3%. We can say that the if the probablity is more than 50% then there is higher chance that the customer leaves the bank.

In [32]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [33]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1509   86]
 [ 185  220]]
