# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [ ]:
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x) #these are independent variables

In [ ]:
print(y) #these are dependent variables

## Taking care of missing data

In [15]:
from sklearn.impute import SimpleImputer #SimpleImputer is the class and imputer is the object of the class
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:, 1:3]=imputer.transform(x[:, 1:3])

In [16]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data
#Categorical encoding is a process of converting categories to numbers.

### Encoding the Independent Variable

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

C:\Users\tarunbanny\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [27]:
print(x)

[[0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
# https://www.analyticsvidhya.com/blog/2020/03/one-hot-encoding-vs-label-encoding-using-scikit-learn/ 
#We can know the difference between over here

In [30]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state= 1)

In [34]:
print(x_train) #for 8 customers

[[1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]]


In [36]:
print(x_test) # rest 2 customers out of 10

[[1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [38]:
print(y_train) # purchase decisions

[0 1 0 0 1 1 0 1]


In [39]:
print(y_test) # purchase desicions of 2 customers

[0 1]


## Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:]= sc.fit_transform(x_train[:, 3:])
x_test[:, 3:]= sc.transform(x_test[:, 3:])


In [46]:
print(x_train)

[[1.0 0.0 1.0 -0.7745966692414833 -0.5773502691896258 1.2909944487358056
  -0.19159184384578554 -1.0781259408412427]
 [1.0 0.0 1.0 -0.7745966692414833 1.7320508075688774 -0.7745966692414833
  -0.014117293757057846 -0.07013167641635404]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.7745966692414833
  0.5667085065333239 0.6335624327104546]
 [1.0 0.0 1.0 -0.7745966692414833 -0.5773502691896258 1.2909944487358056
  -0.3045301939022487 -0.307866172742979]
 [1.0 0.0 1.0 -0.7745966692414833 -0.5773502691896258 1.2909944487358056
  -1.901801144700799 -1.4204636155515822]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.7745966692414833
  1.1475343068237056 1.2326533634535488]
 [1.0 0.0 1.0 -0.7745966692414833 1.7320508075688774 -0.7745966692414833
  1.4379472069688966 1.5749910381638883]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.7745966692414833
  -0.7401495441200352 -0.5646194287757336]]


In [44]:
print(x_test)

[[1.0 0.0 1.0 -0.7745966692414835 1.7320508075688774 -0.7745966692414835
  -1.4661817944830127 -0.9069571034860731]
 [0.0 1.0 0.0 1.2909944487358058 -0.5773502691896258 -0.7745966692414835
  -0.44973664397484425 0.20564033932253029]]
